server:
  port: 8182

#darasourse config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/reldb
#    driver-class-name: org.postgresql.Driver
    username: postgres
    password: pass
  jpa:
    properties:
      show_sql: true
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    #        enable_lazy_load_no_trans: true  # Anti-Pattern  # Activate Eager fetching  => spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false # Anti-Pattern This will disable OSIV so that you can handle the LazyInitializationException the right way.