server:
  port: 8182

#darasourse config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/reldb
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        enable_lazy_load_no_trans: true  # Anti-Pattern  # Activate Eager fetching  => spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
    hibernate:
      ddl-auto: create
#    open-in-view: false # Anti-Pattern This will disable OSIV so that you can handle the LazyInitializationException the right way.