server:
  port: 8182

#darasourse config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/reldb
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create